### ISSUE TITLE
The installation by go failed

### ISSUE THREAD

**Issue by gobomb** [xwjdsh/fy#1]
The installation command way by go should be `go get -u github.com/xwjdsh/fy/cmd/fy`.

If i execute this command from README.md: `go get -u github.com/xwjdsh/cmd/fy`, it would has error like this: `fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/xwjdsh/cmd/fy: exit status 128`

**Comment by xwjdsh** [comment]
Thank you, updated :)
