### ISSUE TITLE
请问能不能直接展示翻译结果

### ISSUE THREAD

**Issue by haoduck** [xwjdsh/fy#14]
![image](https://user-images.githubusercontent.com/56804964/170584471-1b8368f6-aaa7-4b57-831a-dc149cf54c64.png)
就是图里这样只要圈圈里的翻译结果，不要展示翻译源了

**Comment by xwjdsh** [comment]
现在好像不行，我加个 `-q` 吧，不展示 source。

**Comment by xwjdsh** [comment]
https://github.com/xwjdsh/fy/commit/e3374b64e20047d358652d6d7c4408e8104bbc69

<img width="480" alt="image" src="https://user-images.githubusercontent.com/11025519/171083212-171e1804-e397-4ebc-8535-3fb58d7d26e8.png">

**Comment by haoduck** [comment]
> [e3374b6](https://github.com/xwjdsh/fy/commit/e3374b64e20047d358652d6d7c4408e8104bbc69)
> 
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/11025519/171083212-171e1804-e397-4ebc-8535-3fb58d7d26e8.png">

大佬牛批
