### ISSUE TITLE
命令不支持 -s 参数，Windows 下 也不接受回车输入

### ISSUE THREAD

**Issue by QiWei** [xwjdsh/fy#7]
命令中没有 -s 参数，Windows 下也不支持回车输入，只能通过管道输入。
另：是否支持使用代理？

**Comment by xwjdsh** [comment]
> 命令中没有 -s 参数

`-s` 应该某次修改删掉了然后没更新文档，想了下还是有用，又加回来了。

> Windows 下也不支持回车输入，只能通过管道输入。

修改了，用 v0.4.13.

> 是否支持使用代理？

可以用 `https_proxy`， 比如 `https_proxy='127.0.0.1:1087' ./fy xxx`.

---

🙏 感谢你的反馈。我也发现有的翻译有点问题，会在之后比较空闲的时候来改。
